### ISSUE TITLE
Direct to codeforces official page

### ISSUE THREAD

**Issue by Chromicle** [Chromicle/Codeforces#16]
By clicking on the contest direct to the particular contest of the codeforces official page through intetnt to browser  
you can get the URL from codeforces API

**Comment by jaindiv26** [comment]
I'll work on this.

**Comment by Chromicle** [comment]
yeah proceed @jaindiv26

**Comment by jaindiv26** [comment]
@Chromicle Please provide the sample URL for redirecting to a specific contest.

**Comment by jaindiv26** [comment]
@Chromicle Any updates ?

**Comment by Chromicle** [comment]
> @Chromicle Any updates ?

yeah, while fetching data you can fetch the contest id also it looks like `"contestId":777` so with the help of contest id you can directly give some browser intent to `https://codeforces.com/contest/777`

**Comment by jaindiv26** [comment]
Okay, got it. I'll submit a PR soon.
