### ISSUE TITLE
Delete reductant methods and objects

### ISSUE THREAD

**Issue by Chromicle** [Chromicle/Codeforces#2]
There are so many reductant methods and objects are there please remove them

**Comment by pshkrh** [comment]
I'll work on this.

**Comment by Chromicle** [comment]
> I'll work on this.

yeah proceed @pshkrh

**Comment by pshkrh** [comment]
@Chromicle the entire class RatingAsync is unused. Do you want to keep it or remove it?

**Comment by Chromicle** [comment]
> @Chromicle the entire class RatingAsync is unused. Do you want to keep it or remove it?

No, we are using it to for contest rating right so, we have to keep it
