### ISSUE TITLE
Fetch the user info

### ISSUE THREAD

**Issue by Chromicle** [Chromicle/Codeforces#20]
While fetching the contests show the user info also 
you can fetch the user info from if user handle is sandeshghanta the Api looks like this  `https://codeforces.com/api/user.info?handles=sandeshGhanta`

**Comment by rajkumaar23** [comment]
I would like to contribute to this feature. Assign me this ?

**Comment by Chromicle** [comment]
> I would like to contribute to this feature. Assign me this ?

yeah proceed @rajkumaar23

**Comment by rajkumaar23** [comment]
Hey, would you like me to make any changes with my commit ?

**Comment by rajkumaar23** [comment]
Hey, close this issue ?
