### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by Chromicle** [Chromicle/Codeforces#21]
Add the proper README.md
Take the reference `https://github.com/amfoss/TempleApp`

**Comment by Chromicle** [comment]
@jaindiv26 can you please work on this issue

**Comment by sriramdasavage** [comment]
Can I take this

**Comment by Chromicle** [comment]
Yeah, but please study project properly I gave one reference link please go on that way

**Comment by jaindiv26** [comment]
@sriramdasavage Go ahead.

**Comment by Chromicle** [comment]
@sriramdasavage are you still working on this

**Comment by Chromicle** [comment]
As there is no response from @sriramdasavage @jaindiv26 can you work on this please

**Comment by jaindiv26** [comment]
@Chromicle Yeah, I'll work on this.

**Comment by jaindiv26** [comment]
@Chromicle Any updates ?
