### ISSUE TITLE
Add support to fetch preferred handle

### ISSUE THREAD

**Issue by Chromicle** [Chromicle/Codeforces#3]
Currently, we are fetching `sandeshghanta` contests only add support to fetch preferred handle

**Comment by jaindiv26** [comment]
@Chromicle Can you tell me more about this issue?

**Comment by Chromicle** [comment]
yeah, currently the contests which are showing are handle of `sandeshghanta` which you can see from API_URL of `https://codeforces.com/api/user.rating?handle=sandeshghanta`  so before fetching of contests take the handle from the user through edit text and just append the handle at last of the link instead of sandeshghanta so, we can fetch the contests of particular handle

**Comment by jaindiv26** [comment]
Got it. I'll work on this issue and submit the PR soon.

**Comment by Chromicle** [comment]
if you need any help on this issue ask here

**Comment by jaindiv26** [comment]
Okay.
